# Generated by Django 2.0.1 on 2018-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOSTranslator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.CharField(max_length=400)),
            ],
        ),
    ]
